variables:
  GIT_SUBMODULE_STRATEGY: recursive
  BUILD_IMAGE_LINUX_AMD64: $CI_REGISTRY/veilid/ci-cd/veilid-build-linux-amd64:latest

stages:
  - clippy
  - test

############# Clippy Lint
clippy:
  stage: clippy
  image: ${BUILD_IMAGE_LINUX_AMD64}
  tags:
    - linux
    - amd64
  before_script:
    - rustup component add clippy
  script:
    #    - RUSTFLAGS="-D warnings" RUST_BACKTRACE=1 cargo clippy
    - RUST_BACKTRACE=1 cargo clippy

############# Unit Testing
test_linux_amd64:
  stage: test
  image: ${BUILD_IMAGE_LINUX_AMD64}
  tags:
    - linux
    - amd64
  script:
    - dbus-uuidgen > /var/lib/dbus/machine-id
    - mkdir -p /var/run/dbus
    - dbus-daemon --config-file=/usr/share/dbus-1/system.conf --print-address
    - |
      dbus-run-session -- sh << END
      echo | gnome-keyring-daemon --unlock
      cargo test -- --nocapture
      END
    #    - RUSTFLAGS="-D warnings" RUST_BACKTRACE=1 cargo test -- --nocapture
    - RUST_BACKTRACE=1 cargo test -- --nocapture
