variables:
  NO_DOCKER: 1
  BUILDKIT_HOST: tcp://veilid-runner-1:8372
  EARTHLY_EXEC_CMD: "/bin/sh"

earthly:
  stage: build
  image: earthly/earthly:v0.6.28
  tags:
    - linux
    - amd64
  script:
    - earthly --ci -P +package-linux
