services:
  - docker:dind

variables:
  DOCKER_HOST: tcp://docker:2375
  EARTHLY_EXEC_CMD: "/bin/sh"

image: earthly/earthly:v0.6.27

earthly:
  stage: build
  tags:
    - linux
    - amd64
  script:
    - earthly --ci --buildkit-host localhost:8373 -P +package-linux
