earthly:
  stage: build
  image: earthly/earthly:v0.6.28
  tags:
    - linux
    - amd64
  script:
    - earthly --ci --buildkit_host tcp://earthly-buildkit:8372 -e NO_DOCKER=1 --allow-privileged +package-linux
