services:
  - docker:dind

variables:
  DOCKER_HOST: tcp://docker:2375
  EARTHLY_EXEC_CMD: "/bin/sh"

earthly:
  stage: build
  tags:
    - linux
    - amd64
  script:
    - earthly --ci --push -P +package-linux
