- name: Prepare Docker Executor
  become: yes
  hosts: all
  tasks:
    - name: install-dependencies
      ansible.builtin.apt:
        pkg:
        - ca-certificates
        - curl
        - gnupg
        - lsb-release
        - git
    - name: install-docker-sources
      ansible.builtin.script: ./docker-sources.sh
    - name: install-docker-packages
      ansible.builtin.apt:
        pkg:
          - docker-ce
          - docker-ce-cli
          - containerd.io
          - docker-compose-plugin
    - name: install-earthly
      ansible.builtin.script: ./earthly-setup.sh
    - name: copy-config
      ansible.builtin.copy:
        src: ./config/config.toml
        dest: /etc/gitlab-runner/
    - name: copy-config-template
      ansible.builtin.copy:
        src: ./config/template.config.toml
        dest: /tmp/gitlab-runner/
    - name: install-gitlab-runner
      ansible.builtin.script: ./gitlab-runner.sh install
    - name: register-gitlab-runner
      ansible.builtin.script: ./gitlab-runner.sh register
      environment:
        CI_SERVER_URL: "{{ ci_server_url }}"
        REGISTRATION_TOKEN: "{{ regkey }}"
        RUNNER_NAME: "{{ runner_name }}"
