[package]
name = "veilid-cli"
version = "0.1.0"
authors = ["John Smith <jsmith@example.com>"]
edition = "2018"
build = "build.rs"
license = "LGPL-2.0-or-later OR MPL-2.0 OR (MIT AND BSD-3-Clause)"

[[bin]]
name = "veilid-cli"
path = "src/main.rs"

[dependencies]
async-std = { version = "^1.9", features = ["unstable", "attributes"] }
async-tungstenite = { version = "^0.8", features = ["async-std-runtime"] }
cursive = { path = "../external/cursive/cursive", default-features = false, features = ["crossterm-backend", "toml"]}
cursive-flexi-logger-view = { path = "../external/cursive-flexi-logger-view" }
cursive_buffered_backend = { path = "../external/cursive_buffered_backend" }
# cursive-multiplex = "0.4.0"
# cursive_tree_view = "0.6.0"
# cursive_table_view = "0.12.0"
# cursive-tabs = "0.5.0"
clap = "^2.33.2"
directories = "^3"
log = "^0.4"
futures = "^0.3"
serde = "^1.0.122"
serde_derive = "^1.0.122"
parking_lot = "^0.11"
cfg-if = "^0.1"
capnp = "^0.14"
capnp-rpc = "^0.14"
config = { version = "0.10.1", features = ["yaml"] }
anyhow = "^1"
bugsalot = "^0.2"
flexi_logger = "0.17"
thiserror = "^1.0"
crossbeam-channel = "0.5"
veilid-core = { path = "../veilid-core" }

[dev-dependencies]
serial_test = "^0.4"

[build-dependencies]
capnpc = "^0.14"
