[package]
name = "veilid-cli"
version = "0.1.0"
authors = ["John Smith <jsmith@example.com>"]
edition = "2021"
build = "build.rs"
license = "LGPL-2.0-or-later OR MPL-2.0 OR (MIT AND BSD-3-Clause)"

[[bin]]
name = "veilid-cli"
path = "src/main.rs"

[target.'cfg(unix)'.dependencies]
cursive = { path = "../external/cursive/cursive", default-features = false, features = ["ncurses-backend", "toml"]}

[target.'cfg(not(unix))'.dependencies]
cursive = { path = "../external/cursive/cursive", default-features = false, features = ["crossterm-backend", "toml"]}

[dependencies]
async-std = { version = "^1.9", features = ["unstable", "attributes"] }
async-tungstenite = { version = "^0.8", features = ["async-std-runtime"] }
async_executors = { version = "^0", default-features = false, features = [ "async_std" ]}
cursive-flexi-logger-view = { path = "../external/cursive-flexi-logger-view" }
cursive_buffered_backend = { path = "../external/cursive_buffered_backend" }
# cursive-multiplex = "0.4.0"
# cursive_tree_view = "0.6.0"
# cursive_table_view = "0.12.0"
# cursive-tabs = "0.5.0"
clap = "^3"
directories = "^4"
log = "^0"
futures = "^0"
serde = "^1"
serde_derive = "^1"
parking_lot = "^0"
cfg-if = "^1"
capnp = "^0"
capnp-rpc = "^0"
config = { version = "^0", features = ["yaml"] }
bugsalot = "^0"
flexi_logger = "^0"
thiserror = "^1"
crossbeam-channel = "^0"
veilid-core = { path = "../veilid-core" }

[dev-dependencies]
serial_test = "^0"

[build-dependencies]
capnpc = "^0"
