[package]
name = "veilid-server"
version = "0.1.0"
authors = ["John Smith <jsmith@example.com>"]
edition = "2021"
build = "build.rs"
license = "LGPL-2.0-or-later OR MPL-2.0 OR (MIT AND BSD-3-Clause)"

[[bin]]
name = "veilid-server"
path = "src/main.rs"

[features]
default = [ "rt-async-std" ]
rt-async-std = [ "veilid-core/rt-async-std", "async-std", "async-tungstenite/async-std-runtime", "opentelemetry/rt-async-std", "opentelemetry-otlp/grpc-sys"]
tracking = ["veilid-core/tracking"]

[dependencies]
veilid-core = { path = "../veilid-core" }
tracing = { version = "^0", features = ["log", "attributes"] }
tracing-subscriber = { version = "^0", features = ["env-filter"] }
tracing-appender = "^0"
tracing-opentelemetry = "^0"
opentelemetry = { version = "^0" }
opentelemetry-otlp = { version = "^0" }
opentelemetry-semantic-conventions = "^0"
clap = "^3"
async-std = { version = "^1", features = ["unstable"], optional = true }
async-tungstenite = { version = "^0", features = ["async-tls"] }
directories = "^4"
capnp = "^0"
parking_lot = "^0"
capnp-rpc = "^0"
config = { version = "^0", features = ["yaml"] }
failure = "^0"
cfg-if = "^1"
serde = "^1"
serde_derive = "^1"
serde_yaml = "^0"
futures = "^0"
url = "^2"
ctrlc = "^3"
lazy_static = "^1"
bugsalot = "^0"
flume = { version = "^0", features = ["async"] }
rpassword = "^6"
hostname = "^0"

[target.'cfg(windows)'.dependencies]
windows-service = "^0"
ansi_term = "^0"

[target.'cfg(unix)'.dependencies]
daemonize = "^0"
signal-hook = "^0"
signal-hook-async-std = "^0"
nix = "^0"

[target.'cfg(target_os = "linux")'.dependencies]
tracing-journald = "^0"

[dev-dependencies]
serial_test = "^0"

[build-dependencies]
capnpc = "^0"
