[package]
name = "veilid-flutter"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["cdylib", "staticlib", "rlib"]

[dependencies]
veilid-core = { path="../../veilid-core" }
parking_lot = "^0"
log = "^0"
cfg-if = "^1"
backtrace = "^0"
serde_json = "^1"
serde = "^1"
futures = "^0"

# Dependencies for native builds only
# Linux, Windows, Mac, iOS, Android
[target.'cfg(not(target_arch = "wasm32"))'.dependencies]
async-std = { version = "^1", features = ["unstable"] }
anyhow = { version = "^1", features = ["backtrace"] }
allo-isolate = "^0"
ffi-support = "^0"
lazy_static = "^1"

# Dependencies for WASM builds only
[target.'cfg(target_arch = "wasm32")'.dependencies]
wasm-bindgen = "^0"
console_error_panic_hook = "^0"
wee_alloc = "^0"
wasm-logger = "^0"
wasm-bindgen-futures = "^0"
js-sys = "^0"

# Dependencies for Android builds only
[target.'cfg(target_os = "android")'.dependencies]
jni = "^0"

# Dev Dependencies for WASM builds only
[target.'cfg(target_arch = "wasm32")'.dev-dependencies]
wasm-bindgen-test = "^0"

[build-dependencies]
cfg-if = "^1"
